#!/bin/bash

### NIX BEGIN ###

curl \
  --proto '=https' \
  --tlsv1.2 \
  -sSf \
  -L https://install.determinate.systems/nix \
  | sh -s -- install

### NIX END ###


### HOMEBREW BEGIN ###



### HOMEBREW END ###
